# Copyright 2021 Undiscombobulated Chronicles
# SPDX-License-Identifier: BSD 3-Clause

title: Undiscombobulated Chronicles
email: dorta@udchronicles.me
description: >- # this means to ignore newlines until "baseurl:"
  Overly patient, atheist, cooking guy, smoker, and inspired by true events
  on movie screens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://udchronicles.me/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: udchronicles
github_username:  diegohdorta

header_pages:
    - about.markdown
    - tags.markdown


# Build settings
theme: minima
plugins:

  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled: 
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'

keep_files:
  - images
asciidoctor:
  base_dir: :docdir 
  safe: unsafe
  attributes:
    imagesdir: /images
    idprefix: _
    source-highlighter: pygments
    pygments-css: class
    pygments-stylesheet: css/pygment.css
    stem: ''
    icons: font
